### ISSUE TITLE
AoE Projectile Glitch

### ISSUE THREAD

**Issue by Frokraken** [Aidan-acad/Melting_Pot_RoR2#2]
Any enemy projectile that has AoE (overloading elite effect, Mini Mushroom spore cloud, glacial elite death, etc.) most of the time will infinitely duplicate upon hitting an ally and sometimes the glitch might happen if the projectile hits a player as well. It will continue duplicating until the ally or player is dead.

**Comment by Aidan-acad** [comment]
I'm aware of this issue, and will have a new version out later today most likely

**Comment by Aidan-acad** [comment]
Fixed in latest version
