### ISSUE TITLE
Disabling items makes mod stop working

### ISSUE THREAD

**Issue by AndrGarrote** [Aidan-acad/Melting_Pot_RoR2#4]
After disabling some items the mod spam errors at the log and the itens no longer spawn 

[LogOutput.log](https://github.com/Aidan-acad/Melting_Pot_RoR2/files/8548718/LogOutput.log)

[com.Shasocais.MeltingPot.cfg.txt](https://github.com/Aidan-acad/Melting_Pot_RoR2/files/8548727/com.Shasocais.MeltingPot.cfg.txt)
Changed file extension to a type GitHub supports

**Comment by Aidan-acad** [comment]
Ok Ill look into it

**Comment by Aidan-acad** [comment]
Fixed in next release :)
